services:
    # PHP-FPM Service
    php-fpm:
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            - database
            - redis

    # Nginx Service
    nginx:
        image: nginx:alpine
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./nginx/conf.d:/etc/nginx/conf.d/
        depends_on:
            - php-fpm

    # Database Server
    database:
        image: mysql:8.0
        ports:
            - "3307:3306"
        environment:
            - MYSQL_DATABASE=laravel
            - MYSQL_USER=minhnguyen
            - MYSQL_PASSWORD=123456
            - MYSQL_ROOT_PASSWORD=strongrootpassword
            - MYSQL_ALLOW_EMPTY_PASSWORD=1
            - MYSQL_RANDOM_ROOT_PASSWORD=1
        volumes:
            - db-data:/var/lib/mysql

    # Redis Server
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"

volumes:
    db-data: ~

