version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
  db:
    image: mysql:8.0
    environment:
     MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
     MYSQL_ROOT_HOST: '%'
     MYSQL_DATABASE: '${DB_DATABASE}'
     MYSQL_USER: '${DB_USERNAME}'
     MYSQL_PASSWORD: '${DB_PASSWORD}'
     MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mynetwork

volumes:
  mysql_data:

networks:
  mynetwork:
